### PR TITLE
Implement bash-like globbing

### LINKED ISSUE #36: Match against whole path instead of only basename
Forgive me if this functionality already exists and I just don't understand how I would go about it utilizing it.

I am using Ansible and some of the files are in Ansible's YAML format, but do not have an extension or I do not want it to default to using the base YAML syntax.

I am basically looking for the functionality that exists in the ApplySyntax plugin for Sublime.  A direct example would be: http://jamie.ideasasylum.com/2014/08/ansible-syntax-highlighting-sublime/

Is this currently possible with this package? If so, how would I go about duplicating the settings as depicted in that link?

### PR DESCRIPTION
**Pull request by execjosh**
Implement #49 and resolve #36

### CODE REVIEW

**Comment by brandonkal** [comment]
@execjosh could this be merged please?

**Comment by execjosh** [comment]
I suppose so 😄  I think it works 🤔

**Comment by execjosh** [comment]
Does it work for you?

**Comment by execjosh** [comment]
I guess I'll merge this now and make v1.0.0

**Pull request merged**
